Fy/dev
jjkysy/TopFeature pull request #5
Opened 2024-07-05 08:28 UTC by 2020dfff

### Summary :memo:
Use 6 metrics to judge MAS topology, draw the plot

### Details
_Describe more what you did on changes._
1. fig_plot, add function to plot scatter, boxplot
2. for topology(100 graphs each) but not within one graph
3. x-axis: Graph ID or Diameter

2024-07-05 08:51 UTC, jjkysy requested changes
请修改fig_plot里的内容（1）将名字相关的判断语句和固定的名字剥离，可以创造单独的数据格式，用列表或者字典存储。（2）将计算逻辑、画图逻辑、存储逻辑模块化分开，增加可读和可修改性。（3）增加画图模版seabon

2024-07-05 08:51 UTC, jjkysy commented on tpf/fig_plot.py
> +        # if name == "chain_xxx": use circular layout
这个有点奇怪啊，之后如果用这个库画一些别的智能体，不是用这个命名方式命名的咋办？放在这里有点奇怪。

2024-07-05 08:51 UTC, jjkysy commented on tpf/fig_plot.py
> +    def plot_size_features_for_topologies(
plot这块写的稍微有点丑了哈哈哈。（1）把计算的逻辑、画图的逻辑、存储的逻辑分开。模块化一点，之后别人也好用。（2）套用画图模版，e.g., import seaborn as sn 
sn.set_theme('paper', 'whitegrid')

2024-07-05 10:25 UTC, 2020dfff commented
- 存储的逻辑提出来了
- graph feature和topo feature分开写
- 类改实例了

2024-07-05 11:35 UTC, 2020dfff commented
Relogic the calculation, from plot module to evaluation module

2024-07-08 02:32 UTC, jjkysy reviewed
LGTM

2024-07-08 02:33 UTC, jjkysy commented
LGTM

2024-07-08 02:35 UTC, merged